"""Fixture WAV files for layered pipeline tests.

Generated by tests/harness/fixtures/gen_fixtures.py via Fish Audio TTS.
All saved as 48kHz mono int16 WAV (matches the production audio path
into ASR; VAD downsamples internally).
"""
